name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_smart_watch_harmony_os:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.6


flutter:
  uses-material-design: true
